import { PrescriptionEntry, MedicationData } from "@/types/medication";

export let mockPrescriptions: PrescriptionEntry[] = [
  {
    id: "rx1",
    date: "2023-11-01",
    medicationName: "Antibiótico X, Anti-inflamatório Y",
    treatmentDescription: "Tratamento para infecção bacteriana e inflamação.",
    instructions: "Administrar com alimento e bastante água.",
    type: 'simple', // Adicionado tipo
    medications: [
      {
        id: "med1",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Antibiótico X",
        concentration: "250mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "12 horas",
        period: "7 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido, a cada 12 horas, durante 7 dias.",
        generalObservations: "Não interromper o tratamento.",
        totalQuantity: "14",
        totalQuantityDisplay: "14 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med2",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Humana",
        medicationName: "Anti-inflamatório Y",
        concentration: "50mg",
        pharmaceuticalForm: "Cápsula",
        dosePerAdministration: "0.5",
        frequency: "24 horas (1x/dia)",
        period: "5 dias",
        useCustomInstructions: true,
        generatedInstructions: "Meio comprimido uma vez ao dia, por 5 dias, junto com a ração.",
        generalObservations: "",
        totalQuantity: "2.5",
        totalQuantityDisplay: "2.5 cápsula(s)",
        isCollapsed: true,
      },
    ],
  },
  {
    id: "rx-long-test",
    date: new Date().toISOString().split('T')[0],
    medicationName: "Receita de Teste Longa",
    treatmentDescription: "Receita de teste com múltiplos medicamentos para verificação de paginação.",
    instructions: "Esta é uma receita de teste com múltiplos medicamentos para verificar a paginação do PDF.",
    type: 'simple', // Adicionado tipo
    medications: [
      {
        id: "med-long-1",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Antibiótico X",
        concentration: "250mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "12 horas",
        period: "7 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido, a cada 12 horas, durante 7 dias.",
        generalObservations: "Não interromper o tratamento.",
        totalQuantity: "14",
        totalQuantityDisplay: "14 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-2",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Humana",
        medicationName: "Anti-inflamatório Y",
        concentration: "50mg",
        pharmaceuticalForm: "Cápsula",
        dosePerAdministration: "0.5",
        frequency: "24 horas (1x/dia)",
        period: "5 dias",
        useCustomInstructions: true,
        generatedInstructions: "Meio comprimido uma vez ao dia, por 5 dias, junto com a ração.",
        generalObservations: "",
        totalQuantity: "2.5",
        totalQuantityDisplay: "2.5 cápsula(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-3",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Humana",
        medicationName: "Dipirona",
        concentration: "500mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "12 horas",
        period: "10 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido(s), a cada 12 horas, durante 10 dias.",
        generalObservations: "",
        totalQuantity: "20",
        totalQuantityDisplay: "20 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-4",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Agemoxi",
        concentration: "250mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "12 horas",
        period: "21 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido(s), a cada 12 horas, durante 21 dias.",
        generalObservations: "",
        totalQuantity: "42",
        totalQuantityDisplay: "42 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-5",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Giardicid",
        concentration: "50mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "24 horas (1x/dia)",
        period: "5 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido(s), a cada 24 horas (1x/dia), durante 5 dias.",
        generalObservations: "",
        totalQuantity: "5",
        totalQuantityDisplay: "5 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-6",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Nexgard",
        concentration: "10kg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "1",
        frequency: "24 horas (1x/dia)",
        period: "Outro",
        customPeriod: "1 dia (dose unica)",
        useCustomInstructions: false,
        generatedInstructions: "Dê 1 comprimido(s), a cada 24 horas (1x/dia), durante 1 dia (dose unica)",
        generalObservations: "",
        totalQuantity: "1",
        totalQuantityDisplay: "1 comprimido(s)",
        isCollapsed: true,
      },
      {
        id: "med-long-7",
        useType: "Uso Tópico",
        pharmacyType: "Farmácia Veterinária",
        medicationName: "Vetaglos pomada",
        concentration: "",
        pharmaceuticalForm: "Pomada",
        dosePerAdministration: "",
        frequency: "",
        period: "",
        useCustomInstructions: true,
        generatedInstructions: "Aplicar a pomada em toda extensao da ferida",
        generalObservations: "Aplicar apos limpeza com soro",
        totalQuantity: "10",
        totalQuantityDisplay: "10 pomada",
        isCollapsed: true,
      },
      {
        id: "med-long-8",
        useType: "Uso Tópico",
        pharmacyType: "Farmácia Humana",
        medicationName: "Rifocina spray",
        concentration: "",
        pharmaceuticalForm: "Spray",
        dosePerAdministration: "",
        frequency: "",
        period: "",
        useCustomInstructions: true,
        generatedInstructions: "Aplicar apos pomada",
        generalObservations: "",
        totalQuantity: "42",
        totalQuantityDisplay: "42 spray",
        isCollapsed: true,
      },
    ],
  },
  {
    id: "rx-controlled-test",
    date: new Date().toISOString().split('T')[0],
    medicationName: "Rivotril",
    treatmentDescription: "Tratamento para ansiedade severa.",
    instructions: "Manter fora do alcance de crianças.",
    type: 'controlled', // Exemplo de receita controlada
    pharmacistName: "Dra. Farmacêutica Exemplo",
    pharmacistCpf: "123.456.789-00",
    pharmacistCfr: "CRF-SP 12345",
    pharmacistAddress: "Rua da Farmácia, 500, Bairro - Cidade",
    pharmacistPhone: "(11) 99999-8888",
    medications: [
      {
        id: "med-controlled-1",
        useType: "Uso Oral",
        pharmacyType: "Farmácia Humana",
        medicationName: "Rivotril",
        concentration: "2mg",
        pharmaceuticalForm: "Comprimido",
        dosePerAdministration: "0.25",
        frequency: "12 horas",
        period: "30 dias",
        useCustomInstructions: false,
        generatedInstructions: "Dê 0.25 comprimido, a cada 12 horas, durante 30 dias.",
        generalObservations: "Uso contínuo, não interromper abruptamente.",
        totalQuantity: "15",
        totalQuantityDisplay: "15 comprimido(s)",
        isCollapsed: true,
      },
    ],
  },
];